services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB: flows_manager
      MONGODB_COLLECTION: flows
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
