from typing import Protocol

from models.flow import FlowConfigSchema


class FlowLoaderProtocol(Protocol):
    async def load(self, flow_id: str) -> FlowConfigSchema: ...
    async def list_all(self) -> list[FlowConfigSchema]: ...
    async def create(self, flow: FlowConfigSchema) -> FlowConfigSchema: ...
    async def delete(self, flow_id: str) -> None: ...
